version: 2
updates:

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: develop
    schedule:
      interval: "weekly"
      # Check for npm updates at 9am UTC
      time: "09:00"

  - package-ecosystem: maven
    directory: "/server"
    target-branch: develop
    schedule:
      interval: "weekly"
      # Check for npm updates at 9am UTC
      time: "09:00"

  - package-ecosystem: npm
    directory: "/client"
    target-branch: develop
    schedule:
      interval: "weekly"
      # Check for npm updates at 9am UTC
      time: "09:00"
