version: "3"

services:
  app:
    restart: always
    env_file:
      - conf/app/app.env

  nginx:
    image: jonasal/nginx-certbot:latest-alpine
    restart: always
    env_file:
      - conf/nginx/nginx.env
    volumes:
      - ./conf/nginx/hosting.conf.template:/etc/nginx/templates/default.conf.template
      - nginx_volume:/etc/letsencrypt
    ports:
      - "443:443"

  mariadb:
    restart: always

volumes:
  nginx_volume: