version: "3"

services:
  app:
    restart: always

  nginx:
    image: jonasal/nginx-certbot:latest-alpine
    restart: always
    environment:
      HOSTNAME: ${HOSTNAME}
      CERTBOT_EMAIL: ${CERT_MAIL}
      STAGING: ${CERT_STAGING:-0}
      DEBUG: ${CERT_DEBUG:-0}
    volumes:
      - ./hosting.conf.template:/etc/nginx/templates/default.conf.template
      - nginx_volume:/etc/letsencrypt
    ports:
      - "443:443"

  mariadb:
    restart: always

volumes:
  nginx_volume: