name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: false

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Login to GitHub Registry
        uses: docker/login-action@v1
        with:
          username: kokorin
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Detect release version
        id: get-version
        run: |
          release_version=$(git log -1 --format=%as)
          echo "::set-output name=release_version::$release_version"

      - name: Pull
        run: docker-compose -f docker-compose.yml pull

      - name: Build
        run: |
          docker-compose -f docker-compose.yml build
          VERSION=${{ steps.get-version.outputs.release_version }} docker-compose -f docker-compose.yml build

      - name: Push
        run: |
          docker-compose -f docker-compose.yml push
          VERSION=${{ steps.get-version.outputs.release_version }} docker-compose -f docker-compose.yml push

      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-conf.yml
          name: ${{ steps.get-version.outputs.release_version }}
          tag: R${{ steps.get-version.outputs.release_version }}
          version: ${{ steps.get-version.outputs.release_version }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
